let myArray = [];
console.log(myArray);
myArray.push('yam');
console.log(myArray);
myArray.push('bread');
console.log(myArray);
myArray.push('Garri');
console.log(myArray);
myArray.pop();
console.log(myArray);
myArray.shift();  
console.log(myArray);
myArray.unshift('Garri');
console.log(myArray); 